/*
by Jakub Wawak 2021
kubawawak@gmail.com
all rights reserved
 */
package user_interface;

import com.mashape.unirest.http.exceptions.UnirestException;
import configuration.Configuration;
import connector.Connector;
import connector.Parser;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 *Object for creating configuration file
 * @author jakubwawak
 */
public class configuration_window extends javax.swing.JFrame {

    /**
     * Creates new form configuration_window
     */
    Configuration configuration;
    
    public configuration_window(Configuration configuration) {
        this.configuration = configuration;
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setResizable(false);
        load_window();
        setVisible(true);
    }
    
    /**
     * Function for loading window
     */
    void load_window(){
        label_version.setText("ENTRC_SHELF");
        if ( !configuration.file_found ){
            button_question.setEnabled(false);
        }
        if ( configuration.error ){
            field_url.setText("");
            field_apptoken.setText("");
            field_shelf_name.setText("");
        }
        else{
            if ( configuration.standard_file ){
                field_url.setText(configuration.url);
                field_apptoken.setText(configuration.apptoken);
                field_shelf_name.setText("");
                field_url.setEnabled(false);
                field_apptoken.setEnabled(false);
            }
            else{
                field_url.setText(configuration.url);
                field_apptoken.setText(configuration.apptoken);
                field_shelf_name.setText(configuration.entrc_ic_drawer_code);
                field_url.setEnabled(false);
                field_apptoken.setEnabled(false);
                field_shelf_name.setEnabled(false);
            }
        }
    }
    
    /**
     * Function for validating fields
     * @return Boolean
     */
    boolean validate_fields(){
        ArrayList<JTextField> fields = new ArrayList<>();
        fields.add(field_url);
        fields.add(field_shelf_name);
        fields.add(field_apptoken);
        
        for(JTextField field : fields){
            if ( field.getText().equals("")){
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        field_url = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        field_apptoken = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        field_shelf_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        button_load_config_file = new javax.swing.JButton();
        button_close = new javax.swing.JButton();
        label_version = new javax.swing.JLabel();
        button_question = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        field_url.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        field_url.setText("http://XXXXX");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("entrc_api url:");

        field_apptoken.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        field_apptoken.setText("apptoken");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("apptoken:");

        field_shelf_name.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        field_shelf_name.setText("SHELF_NAME");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("shelf CODE:");

        button_load_config_file.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button_load_config_file.setText("LOAD CONFIG FILE");
        button_load_config_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_load_config_fileActionPerformed(evt);
            }
        });

        button_close.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button_close.setText("X");
        button_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_closeActionPerformed(evt);
            }
        });

        label_version.setText("ENTRC_SHELF");

        button_question.setText("?");
        button_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_questionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_load_config_file, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addComponent(label_version))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(button_question)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_close, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(field_shelf_name, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                            .addComponent(field_apptoken)
                            .addComponent(field_url))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button_close, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_version))
                    .addComponent(button_question, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_url, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_apptoken, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_shelf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(button_load_config_file, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_closeActionPerformed
        dispose();
    }//GEN-LAST:event_button_closeActionPerformed

    private void button_load_config_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_load_config_fileActionPerformed
        if ( validate_fields() ){
            configuration.entrc_ic_drawer_code = field_shelf_name.getText();
            Connector connector = new Connector(configuration);
            try{
                Parser parser = new Parser(connector.health());
                new message_window(this,true,"Połączono z entrcAPI\nwersja:"+parser.get_string("program_version"),"API Podłączone");
                // main window ready to connect
                // ready to load drawer content
                new main_window(connector,configuration);
                dispose();
            } catch (UnirestException ex) {
                new message_window(this,true,"Błąd\n"+ex.toString(),"Błąd aplikacji");
                dispose();
                // error checking connection to the database
            } catch(NullPointerException e){
                new message_window(this,true,"Żądany serwer API nie odpowiada","Błąd połączenia");
            }
        }
        else{
            new message_window(this,true,"Błędnie wypełniony formularz","Błąd formularza");
        }
    }//GEN-LAST:event_button_load_config_fileActionPerformed

    private void button_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_questionActionPerformed
        if ( configuration.file_found)
            new message_window(this,true,"Pobrano konfiguracje z :\n"+configuration.configuration_file_path,"Plik konfiguracyjny");
    }//GEN-LAST:event_button_questionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_close;
    private javax.swing.JButton button_load_config_file;
    private javax.swing.JButton button_question;
    private javax.swing.JTextField field_apptoken;
    private javax.swing.JTextField field_shelf_name;
    private javax.swing.JTextField field_url;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label_version;
    // End of variables declaration//GEN-END:variables
}
